### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by rgbayrak** [bruAristimunha/Synthetic-Sleep-EEG-Signal-Generation-using-Latent-Diffusion-Models#1]
Hi @bruAristimunha, will you release the code soon? We want to use your paper for our hands-on journal club, without code, I can't add it to the list.

**Comment by bruAristimunha** [comment]
Dear prof @rgbayrak,

Done, but I am not sure if the code is good for a hands-on.

Have a nice day!

Fyi @JessyD
