### ISSUE TITLE
Question about train_Idm.py

### ISSUE THREAD

**Issue by Augensternzyw** [bruAristimunha/Synthetic-Sleep-EEG-Signal-Generation-using-Latent-Diffusion-Models#2]
Hello, where is generative.networks generated, I don't see it in the original folder.
from generative.networks.nets import DiffusionModelUNet
from generative.networks.nets import AutoencoderKL
from generative.networks.schedulers import DDPMScheduler

**Comment by bruAristimunha** [comment]
Hi @Augensternzyw,

This is a dependency, like numpy and scipy. It is not in the repository but is part of the open-source project that other authors of this project developed, called monai-generative. 

https://github.com/bruAristimunha/Synthetic-Sleep-EEG-Signal-Generation-using-Latent-Diffusion-Models/blob/83b4d977e05f156437059dc1ed935cc46d4319b3/requirements.txt#L12

You can find the original repository here:
https://github.com/Project-MONAI/GenerativeModels
