### ISSUE TITLE
There is a file missing.

### ISSUE THREAD

**Issue by Tony-comments** [bruAristimunha/Synthetic-Sleep-EEG-Signal-Generation-using-Latent-Diffusion-Models#4]
Dear authors:
When I run this file named train_autoencoder.py,I encountered a problem，which is **FileNotFoundError: [Errno 2] No such file or directory: '/project/config/config_encoder_eeg.yaml' .**

Could you provide this file in your repo?

Thanks a lot!

Tony

**Comment by Tony-comments** [comment]
Dear authors:
When I run this file named train_autoencoder.py,I encountered a problem，which is **FileNotFoundError: [Errno 2] No such file or directory: '/project/config/config_encoder_eeg.yaml' .**

Could you provide this file in your repo?

Thanks a lot!

Tony

**Comment by bruAristimunha** [comment]
Hey @Tony-comments,

The file is here: https://github.com/bruAristimunha/Synthetic-Sleep-EEG-Signal-Generation-using-Latent-Diffusion-Models/blob/main/config/config_ldm.yaml

You will need to upload all the paths to make the code work on your computer. Unfortunately, I don't have the time available to make this code more user-friendly. 

Therefore, a good knowledge of Python and Pytorch is necessary to run the code, and I estimate that it will take at least two weeks of daily hard work to adapt to a different infrastructure if you are not using docker and runai. I particularly recommend using Docker, and Container so you don't have to make adaptations.
